version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: eventnest
      POSTGRES_PASSWORD: eventnest_dev
      POSTGRES_DB: eventnest_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://eventnest:eventnest_dev@db:5432/eventnest_development
      RAILS_ENV: development
      SECRET_KEY_BASE: dev_secret_key_base_for_jwt_tokens_only

volumes:
  pgdata:
  bundle_cache:
